### PR TITLE
Add Dev Container

### PR DESCRIPTION
**Pull request by potatoqualitee**
the compose file is a little more challenging, so i'll add it to the next PR

### CODE REVIEW

**Comment by potatoqualitee** [comment]
Dev Containers are the Best. Here's a step by step

Open VS Code, get prompted

image

Reopen and let it setup. Make sure you dont already have a node_modules folder (I'm guessing, again, not a node dev)

image

Next hit the Debugger Icon, then in the drop down, pick Node.js 

image

Select run script -> dev

image

Open your browser as prompted in the lower right, woo!

image

Sometimes it takes a lil longer in the dev container than the regular container, I don't know why. Also, this is probably just a starter dev container, maybe node devs add stuff to the .vscode folder.

image

and boom!

image

**Comment by louislva** [comment]
hey! I saw the compose one first - what's the difference between what these do? and does this mean we need to maintain two different ones now?

**Comment by potatoqualitee** [comment]
Hey Louislva, the Dev Container is for developers (it's VS Code specific) and the Compose file is for end-users who just want to run the server locally.

https://containers.dev/

**Comment by potatoqualitee** [comment]
k this has both the updated dev container with postgres for devs and compose with postgres for end-users (they publish ports differently which is why it needs to be different). I also tested it entirely and it works

image

dev containers, btw, also enable GitHub Codespaces 🥳  That's VS Code on the web, GH gives 60 hours a month free.

image


image

image

https://github.com/features/codespaces

**Comment by potatoqualitee** [comment]
fixes #6 😅

**Review by louislva — APPROVED** [review]

**Comment by louislva** [comment]
This looks dope! Merging, thanks 🙏

**Pull request merged**
