### PR TITLE
Add Docker Compose

### LINKED ISSUE #3: docker-compose to self host this please?
Any chance we can self host this via a simple docker-compose?

### PR DESCRIPTION
**Pull request by potatoqualitee**
Fixes #3 

Note that I'm not a node developer and don't know if I should delete that lock but it complained when I didn't.

### CODE REVIEW

**Comment by potatoqualitee** [comment]
`docker compose up -d`

image


image

**Comment by louislva** [comment]
I think that looks good! Would it be possible to get a PostgreSQL server in there too?

**Comment by potatoqualitee** [comment]
Sure can! Can you give me some context and I'll modify the compose. Like, where in the code does it hook into Postgres?

**Comment by louislva** [comment]
the file is: /helpers/db.ts

it basically just takes a connection string from the environment variable, and connects.

the code defining the tables is in /db.sql

**Pull request merged**
